"""Curated memorable NBA players (3+ franchises in our dataset)."""

from __future__ import annotations

# Household names, All-Stars, and widely recognized journeymen (1980–present).
NOTABLE_PLAYER_NAMES: tuple[str, ...] = (
    "LeBron James",
    "Carmelo Anthony",
    "Dwight Howard",
    "Rajon Rondo",
    "Chris Paul",
    "James Harden",
    "Kevin Durant",
    "Russell Westbrook",
    "Blake Griffin",
    "DeAndre Jordan",
    "Vince Carter",
    "Tracy McGrady",
    "Allen Iverson",
    "Shaquille O'Neal",
    "Ray Allen",
    "Paul Pierce",
    "Kevin Garnett",
    "Jason Kidd",
    "Steve Nash",
    "Dwyane Wade",
    "Chris Bosh",
    "Amar'e Stoudemire",
    "Chauncey Billups",
    "Ben Wallace",
    "Rasheed Wallace",
    "Jermaine O'Neal",
    "Antonio McDyess",
    "Shawn Marion",
    "Joe Johnson",
    "Jamal Crawford",
    "Lou Williams",
    "Trevor Ariza",
    "Jeff Green",
    "Isaiah Thomas",
    "Derrick Rose",
    "Jimmy Butler",
    "Kyle Lowry",
    "DeMar DeRozan",
    "Paul George",
    "Kawhi Leonard",
    "Jim Jackson",
    "Chucky Brown",
    "Joe Smith",
    "Garrett Temple",
    "Ish Smith",
    "Anthony Tolliver",
    "Jeff McInnis",
    "Baron Davis",
    "J.R. Smith",
    "Quinn Cook",
    "JaVale McGee",
    "Tyson Chandler",
    "Marcus Morris",
    "Goran Dragić",
    "Brook Lopez",
    "George Hill",
    "Kevin Martin",
    "Cory Joseph",
    "Patrick Beverley",
    "Eric Bledsoe",
    "Gerald Wallace",
    "Jason Richardson",
    "Corey Maggette",
    "Andre Miller",
    "Raymond Felton",
    "Raja Bell",
    "Boris Diaw",
    "Nazr Mohammed",
    "DeMarcus Cousins",
    "John Wall",
    "Bobby Portis",
    "Jeremy Lin",
    "Pascal Siakam",
    "Kyle Korver",
    "Al Horford",
    "Kirk Hinrich",
    "Dennis Smith Jr.",
    "Justin Holiday",
    "Langston Galloway",
    "Torrey Craig",
    "Cameron Johnson",
    "Quentin Richardson",
    "Earl Boykins",
    "Marcus Camby",
    "Anthony Carter",
    "Reggie Evans",
    "Larry Hughes",
    "Drew Gooden",
    "Ben McLemore",
    "Marcus Thornton",
    "Danuel House Jr.",
    "Avery Bradley",
    "Stephen Jackson",
    "Jared Dudley",
    "Mike Muscala",
    "Austin Rivers",
    "Ryan Anderson",
    "Gerald Green",
    "Joe Harris",
    "Dennis Schröder",
    "D.J. Augustin",
    "Carl Landry",
    "Eric Gordon",
    "Nick Van Exel",
    "Doug Christie",
    "Metta World Peace",
    "Lamar Odom",
    "Caron Butler",
    "Antawn Jamison",
    "Gilbert Arenas",
    "Mike Bibby",
    "Peja Stojaković",
    "Vlade Divac",
    "Hakeem Olajuwon",
    "Charles Barkley",
    "Scottie Pippen",
    "Dennis Rodman",
    "Robert Parish",
    "Kevin Willis",
    "Muggsy Bogues",
    "Mark Jackson",
    "Mark Price",
    "Terrell Brandon",
    "Mitch Richmond",
    "Tim Hardaway",
    "Alonzo Mourning",
    "Dikembe Mutombo",
    "Patrick Ewing",
    "Dominique Wilkins",
    "Spud Webb",
    "Moses Malone",
    "Otis Thorpe",
    "Sam Cassell",
    "Michael Finley",
    "Juwan Howard",
    "Calvin Booth",
    "Rod Strickland",
    "Steve Francis",
    "Cuttino Mobley",
)


def resolve_notable_ids(players_by_name: dict[str, str]) -> set[str]:
    """Map curated names → player_id for names present in the DB."""
    ids: set[str] = set()
    for name in NOTABLE_PLAYER_NAMES:
        pid = players_by_name.get(name)
        if pid:
            ids.add(pid)
    return ids
